Add tests for aliases shared across documents
This test fails as the code uses only one anchor map for the whole stream,
which is not correct as anchors are only shared within a single document.

--- FAIL: TestDecoderAnchorNotSharedAcrossDocuments (0.00s)
    yaml_test.go:755: got nil; want error matching "go-yaml load error in composer at L4.C1: unknown anchor 'foo' referenced"